### ISSUE TITLE
Account info metrics are only sourced from a single server

### ISSUE THREAD

**Issue by protochron** [nats-io/nats-surveyor#117]
It looks like the way that nats surveyor is configured right now, it will only attempt to receive a single response from the NATS cluster over `$SYS.REQ.ACCOUNT.${account_id}.INFO`.

What it should do instead is request up to `numServers` responses from that topic and aggregate the results as needed.

**Comment by ColinSullivan1** [comment]
Closing this issue, please re-open this if you still encounter the behavior you were seeing.

**Comment by protochron** [comment]
@ColinSullivan1 We're using 0.4.0, which is the last released version. I'm happy to compile and run surveyor from source, but it seems like you may want to cut a new release
