### ISSUE TITLE
Use Compression for Requests

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats-surveyor#181]
The Stats endpoints support compression either via Snappy or GZip, example:

```
nats req --header='Accept-Encoding: snappy' '$SYS.REQ.SERVER.PING.CONNZ' ''
```

```
nats req --header='Accept-Encoding: gzip' '$SYS.REQ.SERVER.PING.CONNZ' ''
```

Let's use `snappy` compression for requests here, since it may be less resource intensive than GZip.  So add `Accept-Encoding: snappy` to the requests, and use a Snappy s2 decoder

**Comment by samuelattwood** [comment]
Resolved in #183
