### ISSUE TITLE
Surveyor in K8s "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by saschavusatjuk** [nats-io/nats-surveyor#219]
### What version were you using?

nats-server version: 2.9.8
surveyor: latest
clients: not connected atm

### What environment was the server running in?

Using microk8s on WSL2 Ubuntu and Windows11
nats-server uses: nats:alpine3.16

### Is this defect reproducible?

I was trying to integrate nats-surveyor into k8s without authentication i get: `[WARN] Error unmarshalling statz json: unexpected end of JSON input`.

Okey in the ReadMe is written use **System accounts** i enabled SYS as System account with a .conf and also authenticate with the surveyor.

But as soon as I portforward the port and try to curl the metrics i get this error: `panic: runtime error: invalid memory address or nil pointer dereference`

Nats server runs fine. Surveyor crashes.

### Given the capability you are leveraging, describe your expectation?

It should just get me the metrics. I also made it run with docker-compose but in k8s there are problems i did not have with docker-compose.

### Given the expectation, what is the defect you are observing?

I think there is problem with nats-surveyor running inside an k8s cluster

**Comment by saschavusatjuk** [comment]
The error message shows me that the error comes from collector_statz.go around line 920 and 980

**Comment by piotrpio** [comment]
Hello @saschavusatjuk, thanks for creating the issue. Could you please provide the stack trace of the panic? Also, how are you authenticating (creds or user/password)?

**Comment by mtmk** [comment]
@saschavusatjuk are you seeing this against a single nats-server?

I'm seeing the same error when running a single nats server I'm guessing because the meta (`MetaClusterInfo`) isn't there for jetstream as in `sm.Stats.JetStream.Meta.Pending`

https://github.com/nats-io/nats-surveyor/blob/55e094d832c51aeeaa312858ca655c785f5fef55/surveyor/collector_statz.go#L990

**Comment by ripienaar** [comment]
Probsbly fixed by https://github.com/nats-io/nats-surveyor/pull/220

**Comment by saschavusatjuk** [comment]
It was a problem with surveyor running without cluster in version 0.7.0. Here is [my comment](https://github.com/nats-io/k8s/issues/943#issuecomment-2434542737) in the nats-io/k8s repository.

**Comment by mtmk** [comment]
> Probsbly fixed by #220

this fixed it for me 👍
