### ISSUE TITLE
Surveyor does not return metrics when it did not get expected number of responses (expected server count)

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats-surveyor#37]
We have a problem with the nats-surveyor. It is used to monitor a NATS cluster, which has a load balancer in front of it. Therefore the requests are send only to one of two servers normally. We configured the surveyor to expect the maximum number of servers, but because it gets response from server 1 only it waits for response from server 2 idefinitely and does not responed to any metric requests.
When configured with the number of expected servers = maximum - 1, it will return the metrics as expected. The surveyor is running as a local service, using NSSM, on a Windows 2016 Server. Our cluster consists of a on-premise leafnode server connected to a NATS cluster in Azure. The cluster is loadbalanced using NGINX. We have 4 services for NATS, while service 1 and 4 has 2 PODs assigned, services 2 and 3 have only 1 POD assigned. Connections on Client Port will be loadbalanced between NATS Services 1, 2 and 3. Normally only one POD will answer for requests made to NATS Service 1. 
We are using the latest version 0.1.1.

**Comment by ripienaar** [comment]
Hmm we very frequently have not all responses and do not see this situation. Can you show the logs please?

**Comment by ripienaar** [comment]
To expand on this a bit when the expected servers didn’t reply we wait up to the value or timeout for responses. While a poll is going on we prevent another concurrent poll from happening which appears as if it doesn’t respond

If you have a small network with low latency set timeout quite short.

**Comment by wutkemtt** [comment]
Hi,

here is the log:
`2020/08/28 09:24:59 Connected to NATS Deployment: xxx.xxx.xxx.xxx:4222
2020/08/28 09:24:59 No certificate file specified; using http.
2020/08/28 09:24:59 Prometheus exporter listening at http://0.0.0.0:7778/metrics
2020/08/28 09:24:59 Skipping observation startup, no directory configured
2020/08/28 09:25:19 Concurrent access detected and blocked
2020/08/28 09:25:24 Poll timeout after 20s while waiting for 7 responses
2020/08/28 09:25:24 RTTs for responding servers:
2020/08/28 09:25:24 Server [                : nats-prem.company.com :         0.0.0.0 : NAKC6YAX7GTMUXHLNBSZFTCMRQY6UQNTYLS65QQQ3LVHH7TYKCIFDQF6]: 3.9955ms
2020/08/28 09:25:24 Server [                : nats1-5fd9c558c-scppz :         0.0.0.0 : NAIG4VOXUJFHQFHQSSS5PEVTGCQTNKHYSXXURJ3YXD2INYH5ODRS3MHQ]: 19.9963ms
2020/08/28 09:25:24 Server [                : nats2-5b8d6f6f84-zlmsf :         0.0.0.0 : NAVPDHALJKAFVQ7TWSUFWCFVGSWR2BVMEUCDETTFVAD6LWHKH5JDCT6R]: 22.3337ms
2020/08/28 09:25:24 Server [                : nats3-7ff6d765f7-mzq7b :         0.0.0.0 : NDXPXF7P7DPG5FIU7MINE5NBHKKPZI52SB7HMIGLBRFRFM3D2HIJV2O6]: 18.9956ms
2020/08/28 09:25:24 Server [                : nats4-86bb6b766d-dwwft :         0.0.0.0 : NBYMMQOVPJSBOUJNZZIO2OJRDHGNWVH42J4ODGDQMPR3DRWCKFGWE7A4]: 19.9963ms
2020/08/28 09:25:24 Server [                : nats4-86bb6b766d-sndl5 :         0.0.0.0 : NBZXZD673PWHN2A626H34FRFG43BWJG6JPY4KG226ATDTJ764TXX5HON]: 18.9956ms
2020/08/28 09:25:24 Missing servers:
2020/08/28 09:25:24 Expected 7 servers, only saw responses from 6. Missing []
2020/08/28 09:25:49 Concurrent access detected and blocked
2020/08/28 09:25:54 Poll timeout after 20s while waiting for 7 responses
2020/08/28 09:25:54 RTTs for responding servers:
2020/08/28 09:25:54 Server [                : nats-prem.company.com :         0.0.0.0 : NAKC6YAX7GTMUXHLNBSZFTCMRQY6UQNTYLS65QQQ3LVHH7TYKCIFDQF6]: 3ms
2020/08/28 09:25:54 Server [                : nats1-5fd9c558c-scppz :         0.0.0.0 : NAIG4VOXUJFHQFHQSSS5PEVTGCQTNKHYSXXURJ3YXD2INYH5ODRS3MHQ]: 17.9999ms
2020/08/28 09:25:54 Server [                : nats2-5b8d6f6f84-zlmsf :         0.0.0.0 : NAVPDHALJKAFVQ7TWSUFWCFVGSWR2BVMEUCDETTFVAD6LWHKH5JDCT6R]: 19.0008ms
2020/08/28 09:25:54 Server [                : nats3-7ff6d765f7-mzq7b :         0.0.0.0 : NDXPXF7P7DPG5FIU7MINE5NBHKKPZI52SB7HMIGLBRFRFM3D2HIJV2O6]: 17.9999ms
2020/08/28 09:25:54 Server [                : nats4-86bb6b766d-dwwft :         0.0.0.0 : NBYMMQOVPJSBOUJNZZIO2OJRDHGNWVH42J4ODGDQMPR3DRWCKFGWE7A4]: 19.0008ms
2020/08/28 09:25:54 Server [                : nats4-86bb6b766d-sndl5 :         0.0.0.0 : NBZXZD673PWHN2A626H34FRFG43BWJG6JPY4KG226ATDTJ764TXX5HON]: 17.9999ms
2020/08/28 09:25:54 Missing servers:
2020/08/28 09:25:54 Expected 7 servers, only saw responses from 6. Missing []
2020/08/28 09:26:19 Concurrent access detected and blocked
2020/08/28 09:26:24 Poll timeout after 20s while waiting for 7 responses
2020/08/28 09:26:24 RTTs for responding servers:
2020/08/28 09:26:24 Server [                : nats-prem.company.com :         0.0.0.0 : NAKC6YAX7GTMUXHLNBSZFTCMRQY6UQNTYLS65QQQ3LVHH7TYKCIFDQF6]: 2.0003ms
2020/08/28 09:26:24 Server [                : nats1-5fd9c558c-scppz :         0.0.0.0 : NAIG4VOXUJFHQFHQSSS5PEVTGCQTNKHYSXXURJ3YXD2INYH5ODRS3MHQ]: 19ms
2020/08/28 09:26:24 Server [                : nats2-5b8d6f6f84-zlmsf :         0.0.0.0 : NAVPDHALJKAFVQ7TWSUFWCFVGSWR2BVMEUCDETTFVAD6LWHKH5JDCT6R]: 19ms
2020/08/28 09:26:24 Server [                : nats3-7ff6d765f7-mzq7b :         0.0.0.0 : NDXPXF7P7DPG5FIU7MINE5NBHKKPZI52SB7HMIGLBRFRFM3D2HIJV2O6]: 19ms
2020/08/28 09:26:24 Server [                : nats4-86bb6b766d-dwwft :         0.0.0.0 : NBYMMQOVPJSBOUJNZZIO2OJRDHGNWVH42J4ODGDQMPR3DRWCKFGWE7A4]: 19ms
2020/08/28 09:26:24 Server [                : nats4-86bb6b766d-sndl5 :         0.0.0.0 : NBZXZD673PWHN2A626H34FRFG43BWJG6JPY4KG226ATDTJ764TXX5HON]: 18.0002ms
2020/08/28 09:26:24 Missing servers:
2020/08/28 09:26:24 Expected 7 servers, only saw responses from 6. Missing []
`

**Comment by ripienaar** [comment]
Yeah a 20 second poll timeout doesn’t make sense, no nats network will take 20 seconds to deliver results you can make that way lower. Less than prom poll frequency.

**Comment by wutkemtt** [comment]
Sorry for my late answer: Leaving the default timeout of 3s instead of the former 20s custom value solved the problem for me. 
Thanks, issue can be closed.

**Comment by ripienaar** [comment]
Thank you
