### ISSUE TITLE
Poll timeout

### ISSUE THREAD

**Issue by dyvol777** [nats-io/nats-surveyor#49]
Hello!
I want to use nats-surveyor in kubernetes.
I have nats cluster with 3 members.

>     INFO {"server_id":"NB5LCXTUCEZ7AFJVXU2VKKSFEEAKXXI5ATFCCF4UWZJWHGBQZ3VJM5NM","server_name":"nats-test-0","version":"2.2.6","proto":1,"git_commit":"cf433ae","go":"go1.16.4","host":"0.0.0.0","port":4222,"headers":true,"auth_required":true,"max_payload":1048576,"client_id":15,"client_ip":"10.244.163.0","cluster":"jgWXpX2jE9caUlQAOVkDcO","connect_urls":["10.244.87.22:4222","10.244.163.50:4222","10.244.87.9:4222"]}

Its configuration: 

>     # PID file shared with configuration reloader.
>     pid_file: "/var/run/nats/nats.pid"
> 
>     ###############
>     #             #
>     # Monitoring  #
>     #             #
>     ###############
>     http: 8222
>     server_name: $POD_NAME
>     ###################################
>     #                                 #
>     # NATS Full Mesh Clustering Setup #
>     #                                 #
>     ###################################
>     cluster {
>       port: 6222
> 
>       routes = [
>         nats://nats-0.nats.nats.svc:6222,nats://nats-1.nats.nats.svc:6222,nats://nats-2.nats.nats.svc:6222,
>       ]
>       cluster_advertise: $CLUSTER_ADVERTISE
> 
>       connect_retries: 30
>     }
>     
>     ##################
>     #                #
>     # Authorization  #
>     #                #
>     ##################
>     system_account: SYS
>     authorization {
>       users: [
>     {"password":"c","user":"c"},
>       ]
>     }
>     accounts:{"SYS":{"users":[{"password":"changeit","user":"admin"}]},"USERS":{"users":[{"password":"b","user":"a"},{"password":"a","user":"b"}]}}

I build docker container from latest commit in this repository, and try to run it with args:
>  -p "7777" -password=changeit -user=admin -s=nats://nats-test-0.nats-test.nats-test.svc.cluster.local:4222 -c "3"

Logs from it:

>     2021/06/08 14:18:05 NATS_Surveyor - surveyor-5c66bfc459-4djpf connected to NATS Deployment: 10.244.87.22:4222
>     2021/06/08 14:18:05 No certificate file specified; using http.
>     2021/06/08 14:18:05 Prometheus exporter listening at http://0.0.0.0:7777/metrics
>     2021/06/08 14:18:05 Skipping observation startup, no directory configured
>     2021/06/08 14:18:05 Skipping JetStream API Audit startup, no directory configured
>     2021/06/08 14:18:14 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-0 : NB5LCXTUCEZ7AFJVXU2VKKSFEEAKXXI5ATFCCF4UWZJWHGBQZ3VJM5NM]: 476.642µs
>     2021/06/08 14:18:14 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-1 : NDBIMOYAKIPDSNYEIGS7NZ6Z64QLA53JTSOWAHJDUYFYXT64YMAKWTK2]: 701.973µs
>     2021/06/08 14:18:14 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-2 : NCWHDTOGQBSYS3AVERLU3BZ6TGL4ZXMJSNZLW7I5VEAAMVE6LHAHUCVD]: 1.686063ms
>     2021/06/08 14:18:17 Poll timeout after 3s while waiting for 3 responses
>     2021/06/08 14:18:24 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-0 : NB5LCXTUCEZ7AFJVXU2VKKSFEEAKXXI5ATFCCF4UWZJWHGBQZ3VJM5NM]: 400.099µs
>     2021/06/08 14:18:24 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-1 : NDBIMOYAKIPDSNYEIGS7NZ6Z64QLA53JTSOWAHJDUYFYXT64YMAKWTK2]: 652.35µs
>     2021/06/08 14:18:24 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-2 : NCWHDTOGQBSYS3AVERLU3BZ6TGL4ZXMJSNZLW7I5VEAAMVE6LHAHUCVD]: 1.71099ms
>     2021/06/08 14:18:27 Poll timeout after 3s while waiting for 3 responses
>     2021/06/08 14:18:34 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-0 : NB5LCXTUCEZ7AFJVXU2VKKSFEEAKXXI5ATFCCF4UWZJWHGBQZ3VJM5NM]: 551.721µs
>     2021/06/08 14:18:34 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-1 : NDBIMOYAKIPDSNYEIGS7NZ6Z64QLA53JTSOWAHJDUYFYXT64YMAKWTK2]: 794.566µs
>     2021/06/08 14:18:34 Late reply for server [jgWXpX2jE9caUlQAOVkDcO :     nats-test-2 : NCWHDTOGQBSYS3AVERLU3BZ6TGL4ZXMJSNZLW7I5VEAAMVE6LHAHUCVD]: 2.391342ms
>     2021/06/08 14:18:37 Poll timeout after 3s while waiting for 3 responses

After that container exited with code 2. 
What am I doing wrong?

**Comment by ripienaar** [comment]
As the system user can you see what `nats req '$SYS.REQ.SERVER.PING' ''` does? Use the nats cli from the natscli repo

**Comment by dyvol777** [comment]
`~ # nats req '$SYS.REQ.SERVER.PING' '' --user=admin --password=changeit`
  

>   14:47:08 Sending request on "$SYS.REQ.SERVER.PING"
>   14:47:08 Received on "_INBOX.rTcJZQTClSbAbaiMP3UKUX.sSsFc9NR" rtt 719.947µs
>   {"server":{"name":"nats-test-2","host":"0.0.0.0","id":"NCWHDTOGQBSYS3AVERLU3BZ6TGL4ZXMJSNZLW7I5VEAAMVE6LHAHUCVD","cluster":"jgWXpX2jE9caUlQAOVkDcO","ver":"2.2.6","seq":471,"jetstream":false,"time":"2021-06-08T14:47:08.609889493Z"},"statsz":{"start":"2021-06-08T14:16:38.830606048Z","mem":15015936,"cores":12,"cpu":0,"connections":1,"total_connections":2,"active_accounts":2,"subscriptions":108,"sent":{"msgs":519,"bytes":336440},"received":{"msgs":570,"bytes":162275},"slow_consumers":0,"routes":[{"rid":4,"name":"nats-test-0","sent":{"msgs":395,"bytes":266184},"received":{"msgs":447,"bytes":92749},"pending":41},{"rid":5,"name":"nats-test-1","sent":{"msgs":124,"bytes":70256},"received":{"msgs":123,"bytes":69526},"pending":41}]}}

**Comment by dyvol777** [comment]
and i'm sorry, i build not latest commit, because it isn't build with Dockerfile in repo, this is another issue/
I used commit `1721785f5a786f6d21ac6279cbf139d8a772f188`

**Comment by ripienaar** [comment]
ok, what the error says is all 3 machines didnt respond in 3 seconds - increase timeout should fix it right?

**Comment by ripienaar** [comment]
Though tbh if your 3 servers is on a LAN There's no way 3 seconds should be a problem.

**Comment by dyvol777** [comment]
I understand what was happen. 
There were livenessProbe and readinessProbe that used /metrics, and that caused problems.

You could close it.

**Comment by ripienaar** [comment]
👍
