### ISSUE TITLE
Question: What is the difference between this and the prometheus-nats-exporter

### ISSUE THREAD

**Issue by jdrews** [nats-io/nats-surveyor#51]
I noticed there's a repo called [prometheus-nats-exporter](https://github.com/nats-io/prometheus-nats-exporter). At first glance they both export prometheus metrics from a nats server. What is the difference and which one should I use? Thanks!

**Comment by ripienaar** [comment]
Exporter is as typical for prometheus exporter - runs on every node, exports data for that node.

Surveyor gathers data over the NATS protocol for the network and shows it.

The exporter approach is more work, surveyor is easier.  Exporter works always even when networks are split, surveyor suffers under network splits in that it can only monitor what it can reach.

However past that in NATS we now have a number of network wide data - things like streams that move from node to node, advisories published by all servers over NATS and more - exporter cannot receive those nor can it report on them. So there are types of information only Surveyor can report on.
