### ISSUE TITLE
Error unmarshalling statz json

### ISSUE THREAD

**Issue by mustafa-barakat** [nats-io/nats-surveyor#74]
The nats surveyor is always outputting this to logs, any way i could know what's wrong ?

**Comment by bwerthmann** [comment]
what version(s) of nats-surveyor and nats-server are running?

Please attach a sample of the logs, with some line before and some lines after.

**Comment by gambuccigirl** [comment]
I'm seeing this as well.  Don't know if this will help:

   nats server Version:  2.8.2,  surveyor: latest as of (5/13/22) 

 2022/05/13 23:27:31 NATS_Surveyor - a6ff0c88ce6f connected to NATS Deployment: 192.168.112.3:4222
2022-05-13T23:27:31.437307900Z 2022/05/13 23:27:31 No certificate file specified; using http.
2022-05-13T23:27:31.437407600Z 2022/05/13 23:27:31 Prometheus exporter listening at http://0.0.0.0:7777/metrics
2022-05-13T23:27:31.454325200Z 2022/05/13 23:27:31 NATS_Surveyor - a6ff0c88ce6f (jetstream jetstream) connected to NATS Deployment: 192.168.112.3:4222
2022-05-13T23:27:31.454361700Z 2022/05/13 23:27:31 Started JetStream Advisory listener stats on $JS.EVENT.ADVISORY.> for jetstream
2022-05-13T23:27:31.454371700Z 2022/05/13 23:27:31 Started JetStream Metric listener stats on $JS.EVENT.METRIC.> for jetstream
2022-05-13T23:27:31.772857400Z 2022/05/13 23:27:31 Error unmarshalling statz json: unexpected end of JSON input
2022-05-13T23:27:36.771886900Z 2022/05/13 23:27:36 Error unmarshalling statz json: unexpected end of JSON input
2022-05-13T23:27:41.771194200Z 2022/05/13 23:27:41 Error unmarshalling statz json: unexpected end of JSON input
2022-05-13T23:27:46.771428300Z 2022/05/13 23:27:46 Error unmarshalling statz json: unexpected end of JSON input

**Comment by jose-abuin-bruker** [comment]
Hi. Sorry for commenting on a closed issue, but this is happening to me when using **provided docker-compose files** in [main branch](https://github.com/nats-io/nats-surveyor/tree/main/docker-compose) The only modifications I added are:

- Added a service for the nats-server, so I can have everything together in the same docker-compose.
- Removed `-creds /etc/surveyor/SYS.creds` from surveyor service, as it was throwing an error.
- IN `.env` file I set the `NATS_SURVEYOR_SERVERS` var to `nats://nats-server:4222`

All versions are latest from Docker Hub, except the NATS server, which is 2.8.4-alpine3.15

Complete docker-compose file:

    version: "3"
    
    networks:
      monitor-net:
        driver: bridge
    
    services:
    
      nats-server:
        command:
          - "-p"
          - "4222"
          - "-m"
          - "8222"
          - "-js"
          - "-c=/opt/run/simple-server.conf"
        ports:
          - "4222:4222"
          - "8222:8222"
        volumes:
          - ./nats/:/opt/run/
        image: nats:2.8.4-alpine3.15
        container_name: nats-server
        networks:
          - monitor-net
        labels:
          org.label-schema.group: "nats-monitoring"
    
      surveyor:
        image: natsio/nats-surveyor:${SURVEYOR_DOCKER_TAG}
        container_name: nats-surveyor
        restart: always
        ports:
          - "7777:7777"
        volumes:
          - $NATS_SURVEYOR_CREDS:/etc/surveyor/SYS.creds
          - ./observations:/observations
          - ./jetstream:/jetstream
        entrypoint: /nats-surveyor
        command: -c ${NATS_SURVEYOR_SERVER_COUNT} -s "${NATS_SURVEYOR_SERVERS}" --observe /observations --jetstream /jetstream
        networks:
          - monitor-net
        labels:
          org.label-schema.group: "nats-monitoring"
        depends_on:
          - nats-server
    
      prometheus:
        image: prom/prometheus:${PROMETHEUS_DOCKER_TAG}
        user: "1000:1000"
        container_name: prometheus
        restart: always
        volumes:
          - ./prometheus/:/etc/prometheus/
          - $PROMETHEUS_STORAGE:/usr/local/share/prometheus
        command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/usr/local/share/prometheus
        networks:
          - monitor-net
        labels:
          org.label-schema.group: "nats-monitoring"
        depends_on:
          - surveyor
    
      grafana:
        image: grafana/grafana:${GRAFANA_DOCKER_TAG}
        container_name: grafana
        restart: always
        ports:
          - "3000:3000"
        volumes:
          - ./grafana/dashboards:/var/lib/grafana/dashboards
          - ./grafana/provisioning:/etc/grafana/provisioning
        networks:
          - monitor-net
        labels:
          org.label-schema.group: "nats-monitoring"
        depends_on:
          - prometheus


Content of ./nats/simple-server.conf:

    listen: 0.0.0.0:4222
    max_payload: 8MB
    http_port: 8222
    accounts: {
	    SYS: {
		    users: [
			    { user:admin, password:admin }
		    ]
	    }
    }
    system_account=SYS

Any advice on this? Am I doing something wrong or is the same bug again?

Thanks in advance.

**Comment by jose-abuin-bruker** [comment]
Ah, I see! Now it totally working.

Thank you very much!
