### ISSUE TITLE
Update TLS Documentation

### ISSUE THREAD

**Issue by Ryner51** [nats-io/nats-surveyor#85]
In the documentation it shows:

  -tlscacert string
    	Client certificate CA for verification (used with HTTPS).
  -tlscert string
    	Server certificate file (Enables HTTPS).
  -tlskey string
    	Private key for server certificate (used with HTTPS).

However, these params are for the client connection to NATS and not HTTPS

https://github.com/nats-io/nats-surveyor/blob/master/main.go#L49

There should be two sections for tls -- one for client connections and HTTPS in the documentation.

**Comment by caleblloyd** [comment]
This has been fixed:

```
      --http-tlscacert string               Client certificate CA for verification (used with HTTPS).
      --http-tlscert string                 Server certificate file (Enables HTTPS).
      --http-tlskey string                  Private key for server certificate (used with HTTPS).
      --tlscacert string                    Client certificate CA on NATS connections.
      --tlscert string                      Client certificate file for NATS connections.
      --tlskey string                       Client private key for NATS connections.
```
